const mongoose = require("mongoose");

const PropertySchema = new mongoose.Schema({
  AGENT_REF: String,
  ADDRESS_1: String,
  ADDRESS_2: String,
  ADDRESS_3: String,
  TOWN: String,
  POSTCODE1: String,
  POSTCODE2: String,
  FEATURE1: String,
  FEATURE2: String,
  FEATURE3: String,
  FEATURE4: String,
  FEATURE5: String,
  FEATURE6: String,
  FEATURE7: String,
  FEATURE8: String,
  FEATURE9: String,
  FEATURE10: String,
  SUMMARY: String,
  DESCRIPTION: String,
  BRANCH_ID: String,
  STATUS_ID: String,
  BEDROOMS: String,
  BATHROOMS: String,
  LIVING_ROOMS: String,
  PRICE: String,
  PRICE_QUALIFIER: String,
  PROP_SUB_ID: String,
  CREATE_DATE: String,
  UPDATE_DATE: String,
  DISPLAY_ADDRESS: String,
  PUBLISHED_FLAG: String,
  LET_DATE_AVAILABLE: String,
  LET_BOND: String,
  LET_TYPE_ID: String,
  LET_FURN_ID: String,
  LET_RENT_FREQUENCY: String,
  LET_WASHING_MACHINE_FLAG: String,
  LET_DISHWASHER_FLAG: String,
  LET_BURGLAR_ALARM_FLAG: String,
  LET_BILL_INC_WATER: String,
  LET_BILL_INC_GAS: String,
  LET_BILL_INC_ELECTRICITY: String,
  LET_BILL_INC_TV_LICENCE: String,
  LET_BILL_INC_TV_SUBSCRIPTION: String,
  LET_BILL_INC_INTERNET: String,
  TENURE_TYPE_ID: String,
  TRANS_TYPE_ID: String,
  NEW_HOME_FLAG: String,
  MEDIA_IMAGE_00: String,
  MEDIA_IMAGE_01: String,
  MEDIA_IMAGE_TEXT_01: String,
  MEDIA_IMAGE_02: String,
  MEDIA_IMAGE_TEXT_02: String,
  MEDIA_IMAGE_03: String,
  MEDIA_IMAGE_TEXT_03: String,
  MEDIA_IMAGE_04: String,
  MEDIA_IMAGE_TEXT_04: String,
  MEDIA_IMAGE_05: String,
  MEDIA_IMAGE_TEXT_05: String,
  MEDIA_IMAGE_06: String,
  MEDIA_IMAGE_TEXT_06: String,
  MEDIA_IMAGE_07: String,
  MEDIA_IMAGE_TEXT_07: String,
  MEDIA_IMAGE_08: String,
  MEDIA_IMAGE_TEXT_08: String,
  MEDIA_IMAGE_09: String,
  MEDIA_IMAGE_TEXT_09: String,
  MEDIA_IMAGE_10: String,
  MEDIA_IMAGE_TEXT_10: String,
  MEDIA_IMAGE_11: String,
  MEDIA_IMAGE_TEXT_11: String,
  MEDIA_IMAGE_12: String,
  MEDIA_IMAGE_TEXT_12: String,
  MEDIA_IMAGE_13: String,
  MEDIA_IMAGE_TEXT_13: String,
  MEDIA_IMAGE_14: String,
  MEDIA_IMAGE_TEXT_14: String,
  MEDIA_IMAGE_15: String,
  MEDIA_IMAGE_TEXT_15: String,
  MEDIA_IMAGE_16: String,
  MEDIA_IMAGE_TEXT_16: String,
  MEDIA_IMAGE_60: String,
  MEDIA_IMAGE_TEXT_60: String,
  MEDIA_IMAGE_61: String,
  MEDIA_IMAGE_TEXT_61: String,
  MEDIA_FLOOR_PLAN_00: String,
  MEDIA_FLOOR_PLAN_TEXT_00: String,
  MEDIA_FLOOR_PLAN_01: String,
  MEDIA_FLOOR_PLAN_TEXT_01: String,
  UNIPOL_STANDARD: String,
  PROPERTY_WEEK: String,
  TENANT_TYPE: String,
  FEED_SLIDE_01: String,
  FEED_SLIDE_02: String,
  FEED_SLIDE_03: String,
  FEED_SLIDE_04: String,
  FEED_SLIDE_05: String,
  FEED_SLIDE_06: String,
  FEED_SLIDE_07: String,
  FEED_SLIDE_08: String,
  FEED_SLIDE_09: String,
  FEED_SLIDE_10: String,
  FEED_SLIDE_11: String,
  FEED_SLIDE_12: String,
  FEED_SLIDE_13: String,
  FEED_SLIDE_14: String,
  FEED_SLIDE_15: String,
  FEED_SLIDE_16: String,
  MAIN_VIEWER: String,
  EPC_EER: String,
  EPC_EERP: String,
  EPC_EIR: String,
  EPC_EIRP: String,
  TLS_INCENTIVE: String,
  TLS_SOCIALMEDIA: String,
  TLS_LETTING_TYPE: String,
  TLS_LETTING_ADVERTS: String,
  TLS_HOUSEMATES: String,
  TLS_HOUSEMATES_DATE: String,
  has_rooms: { type: Boolean, default: false },
  rooms_from: { type: Number, default: null },
  rooms: { type: Array, default: [] },
  slug: {
    type: String,
    unique: true,
    index: true,
  },
  is_student_property: {
    type: Boolean,
    default: false, // Default to false
  },
});

const PropertyModel = mongoose.model("properties", PropertySchema);

module.exports = PropertyModel;
// export default PropertyModel;
